// export const host = "http://localhost:8000"
export const host = "https://tuongtran-chatapp.herokuapp.com/api"
export const loginRoute = `${host}/auth/login`;
export const registerRoute = `${host}/auth/register`
export const getAllUsers = `${host}/auth/allUsers`
export const getUser = `${host}/auth/getUser`
export const getAllMessages = `${host}/messages/getmsg`
export const addMessage = `${host}/messages/addmsg`
export const setAva = `${host}/auth/setAvatar`
export const logout = `${host}/auth/logout`